/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulpejemplo.vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ulpejemplo.accesoDatos.InscripcionData;
import ulpejemplo.accesoDatos.MateriaData;
import ulpejemplo.entidades.Estudiante;
import ulpejemplo.entidades.Materia;

/**
 *
 * @author marti
 */
public class ConsulEstuMater extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel()
    {
        //debo hacer editable una sola columna de notas
        @Override
        public boolean isCellEditable(int row, int column)
        {
            return false;
        }
    };
    /**
     * Creates new form ConsulEstuMater
     */
    public ConsulEstuMater() {
        initComponents();
        cargarCombo();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLestuPorMate = new javax.swing.JLabel();
        jLselecMater = new javax.swing.JLabel();
        jCBmaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtableEstuPorMate = new javax.swing.JTable();
        jBsalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta de Estudiantes por Materia");

        jLestuPorMate.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLestuPorMate.setText("Consulta de Estudiantes por Materia");

        jLselecMater.setText("Seleccione Materia: ");

        jCBmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmateriasActionPerformed(evt);
            }
        });

        jTtableEstuPorMate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTtableEstuPorMate);

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLestuPorMate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLselecMater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBmaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLestuPorMate)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLselecMater)
                    .addComponent(jCBmaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmateriasActionPerformed
        // TODO add your handling code here:
        //Capturar combo seleccionado
        //Cargar la tabla
        modelo.setRowCount(0); 
        Materia mateSelec = (Materia) jCBmaterias.getSelectedItem();
        //instancio una inscripcionData para acceder a sus metodos
        InscripcionData inscriData = new InscripcionData();
        
        List<Estudiante> estuLista = inscriData.obtenerEstudiantePorMateria(mateSelec.getId_materia());
        
        for (Estudiante aux : estuLista)
        {
            modelo.addRow(new Object[]{aux.getId_estudiante(), aux.getDni(), aux.getApellido(), aux.getNombre()});
        }
    }//GEN-LAST:event_jCBmateriasActionPerformed

    private void cargarCombo()
    {
        //instanciar un MateriaData para acceder a sus métodos
        MateriaData mateData = new MateriaData();
        List<Materia> mateLista = mateData.listarMaterias();
        //con un for each -enhanced for- voy agregando al comboBox
        for (Materia aux: mateLista)
        {
            jCBmaterias.addItem(aux);
        }
    }
    
    private void armarCabeceraTabla()
    {
        modelo.addColumn("Id");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        
        //aviso que este será la representación para la tabla
        jTtableEstuPorMate.setModel(modelo);
    }
    
    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "¿Salir de este formulario?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) 
        {
            // con dispose salimos del internal frame. Para salir x completo: "System.exit(0);"
            this.dispose();
        }
    }//GEN-LAST:event_jBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<Materia> jCBmaterias;
    private javax.swing.JLabel jLestuPorMate;
    private javax.swing.JLabel jLselecMater;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTtableEstuPorMate;
    // End of variables declaration//GEN-END:variables
}
